/** Compact series data — expanded to full HTML at seed time */
export type SeedMeta = {
  slug: string;
  title: string;
  summary: string;
  category: 'money' | 'opportunities' | 'scams' | 'guides';
  series: string;
  part: number;
  reading_minutes: number;
  intro: string;
  bullets: string[];
  steps: string[];
  mistakes: string[];
  nextSlug?: string;
  prevSlug?: string;
};

export const DATA: SeedMeta[] = [
  { slug: 'series-phone-01-honest-start', title: 'Start on your phone: an honest map (Series 1 · Part 1)', summary: 'What make-money-with-a-phone can mean — skills, time, X noise, and a calm beginner path.', category: 'guides', series: 'phone', part: 1, reading_minutes: 12, intro: 'Every week on X people ask how to earn with only a phone. The question is fair. The reply pile often is not: comment-your-wallet posts, pay-to-unlock dashboards, and screenshots nobody can audit. This series assumes you are a beginner who needs skills you can practice without a laptop first — and safety from day one.', bullets: ['Skill for hire: writing, editing, simple design, careful replies', 'Content practice: packaging and consistency on one platform', 'Safety literacy: job traps, wallet traps, fake support', 'Mute seed-phrase asks, pay-to-withdraw balances, countdown pressure', 'Discipline and one practiced skill beat random app hopping'], steps: ['Read this map once fully', 'Decide you will pick one lane in Part 2', 'Mute three noisy accounts this week', 'Open the next part when ready'], mistakes: ['Treating every trending thread as a plan', 'Installing ten apps before finishing one sample', 'Skipping safety until after a loss'], nextSlug: 'series-phone-02-pick-lane' },
  { slug: 'series-phone-02-pick-lane', title: 'Pick one phone lane for 30 days (Series 1 · Part 2)', summary: 'One practice lane so your week is not random apps and zero samples.', category: 'guides', series: 'phone', part: 2, reading_minutes: 11, intro: 'Beginners often try affiliate, airdrops, freelancing, and faceless pages for two days each. Month end: accounts everywhere, proof nowhere. Clients and platforms reward evidence of skill.', bullets: ['Short video edit with CapCut', 'Writing help: captions, product text, outreach', 'UGC-style demos on screen or camera', 'Scam literacy explainers without fearbait'], steps: ['Write one sentence: For 30 days I practice ___ and finish ___ samples', 'Check new opportunities against that sentence', 'Schedule three practice blocks this week'], mistakes: ['Switching lanes after one boring day', 'Choosing a lane you cannot sample in seven days'], prevSlug: 'series-phone-01-honest-start', nextSlug: 'series-phone-03-weekly-system' },
  { slug: 'series-phone-03-weekly-system', title: 'A weekly system on phone only (Series 1 · Part 3)', summary: 'Practice blocks and a light review — systems beat motivation spikes.', category: 'guides', series: 'phone', part: 3, reading_minutes: 11, intro: 'Motivation is a weak engine. Consistency and a boring weekly system beat a heroic weekend then silence — the same lesson serious creators repeat online.', bullets: ['3 days × 45 minutes produce', '1 day × 30 minutes study one strong example', '1 day × 20 minutes review notes', 'Track sessions, finished pieces, one lesson — not stranger screenshots'], steps: ['Put three production blocks on your calendar or notes', 'Download tools on Wi-Fi ahead of time', 'Keep one album or folder named practice'], mistakes: ['Measuring only income before skill exists', 'Skipping review so mistakes repeat'], prevSlug: 'series-phone-02-pick-lane', nextSlug: 'series-phone-04-proof-asset' },
  { slug: 'series-phone-04-proof-asset', title: 'Build one proof asset this week (Series 1 · Part 4)', summary: 'A finished sample beats a long bio — CapCut, Canva, or a one-page guide.', category: 'opportunities', series: 'phone', part: 4, reading_minutes: 12, intro: 'A proof asset shows how you think and deliver. Bios claim. Samples demonstrate. Phone tools are enough for version one.', bullets: ['CapCut vertical clip with captions', 'Canva carousel or checklist', 'Notes app one-page PDF guide', 'One idea, readable text, clear audio or captions'], steps: ['Day 1 outline in five lines', 'Capture or write', 'Edit once', 'Ask one trusted person what was unclear', 'Freeze v1'], mistakes: ['Polishing forever instead of shipping v1', 'Five ideas in one sample'], prevSlug: 'series-phone-03-weekly-system', nextSlug: 'series-phone-05-second-skill' },
  { slug: 'series-phone-05-second-skill', title: 'When to add a second skill (Series 1 · Part 5)', summary: 'Finish the first proof before stacking more apps.', category: 'guides', series: 'phone', part: 5, reading_minutes: 10, intro: 'A second skill is an unlock after proof — not a way to avoid finishing the first lane.', bullets: ['Need: finished sample, about four weeks of notes, clear offer sentence', 'Good pairs: editing+captions, writing+Canva, explainers+scam education', 'Bad: signals+freelance+affiliate+airdrops in one week'], steps: ['Confirm unlock rule', 'Choose creator, scam, or money series next'], mistakes: ['Adding skills to feel productive'], prevSlug: 'series-phone-04-proof-asset', nextSlug: 'series-creator-01-visibility' },
  { slug: 'series-creator-01-visibility', title: 'Visibility is not the whole game (Series 2 · Part 1)', summary: 'Views help — relationships and systems matter when virality fades.', category: 'guides', series: 'creator', part: 1, reading_minutes: 11, intro: 'A spike in views is not a full path. Attention opens doors; delivery, pricing, and trust still have to be built. Thoughtful creators keep stressing relationships after the spike.', bullets: ['Reply to sincere niche comments', 'Keep a list of careful peers', 'Score finished pieces and relationships, not reach alone'], steps: ['Block 15 minutes for replies this week', 'Write three peer accounts you respect'], mistakes: ['Treating smaller accounts as invisible'], nextSlug: 'series-creator-02-one-platform' },
  { slug: 'series-creator-02-one-platform', title: 'One platform first for 60 days (Series 2 · Part 2)', summary: 'Learn one app’s rhythm before cross-posting everywhere.', category: 'guides', series: 'creator', part: 2, reading_minutes: 10, intro: 'Each app teaches different packaging. Cross-posting on day one feels busy and stays shallow.', bullets: ['Camera-ok → short video', 'Writer → threads or carousels', 'Faceless → screen demos + text'], steps: ['Write a 60-day contract: platform, cadence, topic', 'Review only after day 60 unless safety forces change'], mistakes: ['Five platforms with no samples'], prevSlug: 'series-creator-01-visibility', nextSlug: 'series-creator-03-hooks' },
  { slug: 'series-creator-03-hooks', title: 'Hooks that respect the viewer (Series 2 · Part 3)', summary: 'First seconds matter without fake income claims.', category: 'guides', series: 'creator', part: 3, reading_minutes: 11, intro: 'Name the problem, promise a real learning outcome, start the demo immediately. Skeptical audiences punish mismatch.', bullets: ['Plain problem language', 'Specific learning promise', 'Demo in the first seconds', 'Avoid guaranteed-income energy'], steps: ['Rewrite three hooks for your lane', 'Test one on your next clip'], mistakes: ['Titles the video never delivers'], prevSlug: 'series-creator-02-one-platform', nextSlug: 'series-creator-04-capcut' },
  { slug: 'series-creator-04-capcut', title: 'CapCut on phone: a beginner workflow (Series 2 · Part 4)', summary: 'Cuts, captions, export — practice workflow before endless effects.', category: 'guides', series: 'creator', part: 4, reading_minutes: 12, intro: 'Phone-first creators learn mobile editors such as CapCut. The skill is the workflow, not the logo on the app.', bullets: ['Import one clip', 'Cut silence', 'Captions + spelling', 'Vertical export', 'One skill per week: captions, then pacing, then hierarchy'], steps: ['Finish one captioned clip this week', 'Avoid stacking every effect'], mistakes: ['Buying tools before a finished sample'], prevSlug: 'series-creator-03-hooks', nextSlug: 'series-creator-05-batch' },
  { slug: 'series-creator-05-batch', title: 'Batch content without burning out (Series 2 · Part 5)', summary: 'Plan, capture, edit in blocks — stop nightly panic posting.', category: 'guides', series: 'creator', part: 5, reading_minutes: 10, intro: 'Context-switching is expensive. Batching is how steady posters survive without opening another hustle app for dopamine.', bullets: ['Plan five hooks', 'Capture in one sitting', 'Edit two pieces fully'], steps: ['Run one full batch cycle this week'], mistakes: ['Daily what-do-I-post spiral'], prevSlug: 'series-creator-04-capcut', nextSlug: 'series-creator-06-ugc' },
  { slug: 'series-creator-06-ugc', title: 'UGC-style work: skill before audience size (Series 2 · Part 6)', summary: 'Honest demos and walkthroughs — clarity over hype.', category: 'opportunities', series: 'creator', part: 6, reading_minutes: 11, intro: 'Short honest product or app demos can matter even before a huge following. Clarity and true claims still matter more than hype.', bullets: ['20–40 second how-I-use-this clip', 'First sentence states the point', 'Disclose if paid or affiliated later'], steps: ['Record one practice demo this week'], mistakes: ['Invented results'], prevSlug: 'series-creator-05-batch', nextSlug: 'series-algo-01-what-platforms-measure' },
  { slug: 'series-algo-01-what-platforms-measure', title: 'What short-video platforms roughly optimize for (Series 3 · Part 1)', summary: 'Watch time and return visits in plain language.', category: 'guides', series: 'algo', part: 1, reading_minutes: 11, intro: 'You do not need a conspiracy theory. Platforms generally try to keep people watching and returning. Your levers are packaging and retention.', bullets: ['Do people pass the opening?', 'Do they rewatch?', 'Do they return to the account?'], steps: ['Watch your last clip and note the first weak second'], mistakes: ['Chasing secret score myths'], nextSlug: 'series-algo-02-titles' },
  { slug: 'series-algo-02-titles', title: 'Titles and first lines that match the video (Series 3 · Part 2)', summary: 'Promise what you deliver.', category: 'guides', series: 'algo', part: 2, reading_minutes: 10, intro: 'If the video teaches captions, the title should say captions. Mismatch may raise clicks and still fail trust.', bullets: ['Match packaging to content', 'Write three options', 'Pick the one a skeptical friend believes'], steps: ['Rewrite titles on two drafts'], mistakes: ['Bait that the video never pays off'], prevSlug: 'series-algo-01-what-platforms-measure', nextSlug: 'series-algo-03-retention' },
  { slug: 'series-algo-03-retention', title: 'Retention basics for beginners (Series 3 · Part 3)', summary: 'Cut dead air and keep one idea per video.', category: 'guides', series: 'algo', part: 3, reading_minutes: 11, intro: 'Retention is mostly honesty and pacing: remove fluff, show the outcome early, change framing before energy dies.', bullets: ['Delete opening fluff', 'Show outcome early', 'One idea per video'], steps: ['Re-edit one clip with these drills'], mistakes: ['Five lessons in one short'], prevSlug: 'series-algo-02-titles', nextSlug: 'series-algo-04-cadence' },
  { slug: 'series-algo-04-cadence', title: 'Posting cadence you can survive (Series 3 · Part 4)', summary: 'A schedule you keep beats a streak that collapses.', category: 'guides', series: 'algo', part: 4, reading_minutes: 10, intro: 'Three solid posts a week for eight weeks beats daily spam that dies on day six. Pair with batching.', bullets: ['Sustainable weekly count', 'Cut volume not honesty when life explodes'], steps: ['Set a cadence you can keep while tired'], mistakes: ['Hero week then silence'], prevSlug: 'series-algo-03-retention', nextSlug: 'series-algo-05-review' },
  { slug: 'series-algo-05-review', title: 'Review signals without obsession (Series 3 · Part 5)', summary: 'Completion and comments over vanity spikes.', category: 'guides', series: 'algo', part: 5, reading_minutes: 10, intro: 'Weekly questions beat dashboard addiction: where did people leave, which hook rewatched, which comment showed confusion.', bullets: ['Change one variable next week', 'Ignore vanity spikes as strategy'], steps: ['Write a five-line review this week'], mistakes: ['Changing everything at once'], prevSlug: 'series-algo-04-cadence' },
  { slug: 'series-digital-01-one-problem', title: 'Digital products: one problem, one small file (Series 4 · Part 1)', summary: 'Ship a narrow helper — skip the unshipped mega-course.', category: 'opportunities', series: 'digital', part: 1, reading_minutes: 12, intro: 'Giant courses rarely ship. A checklist or template that solves one painful step can be finished and improved from real questions.', bullets: ['CapCut caption checklist', 'Client brief template', 'Scam red-flag one-pager'], steps: ['Write: This helps [person] stop [pain] with [artifact]'], mistakes: ['Building modules before one shipped page'], nextSlug: 'series-digital-02-validate' },
  { slug: 'series-digital-02-validate', title: 'Validate before you polish (Series 4 · Part 2)', summary: 'Three real conversations beat guesswork.', category: 'opportunities', series: 'digital', part: 2, reading_minutes: 10, intro: 'Ask three people who live the problem. If they cannot describe the pain in their words, rethink.', bullets: ['Messy workarounds are a signal', 'Unprompted asks for the file are a signal'], steps: ['Message three people this week'], mistakes: ['Only polling your own head'], prevSlug: 'series-digital-01-one-problem', nextSlug: 'series-digital-03-deliver' },
  { slug: 'series-digital-03-deliver', title: 'Delivery and first pricing experiments (Series 4 · Part 3)', summary: 'Boring delivery. Learning-priced first version.', category: 'opportunities', series: 'digital', part: 3, reading_minutes: 10, intro: 'PDF or simple link first. Automate after real purchases work. First price is for learning.', bullets: ['Track questions and confusion', 'Raise only after the artifact clearly helps'], steps: ['Choose a boring delivery path'], mistakes: ['Building a funnel before a file'], prevSlug: 'series-digital-02-validate', nextSlug: 'series-digital-04-affiliate' },
  { slug: 'series-digital-04-affiliate', title: 'Affiliate basics with honest disclosure (Series 4 · Part 4)', summary: 'One offer, real disclosure, no fake screenshots.', category: 'opportunities', series: 'digital', part: 4, reading_minutes: 11, intro: 'Distribution talk gets loud on X. Trust still decides who people click twice. Disclose relationships and never fabricate proof.', bullets: ['One offer while learning', 'Say who the tool is not for'], steps: ['Pick one tool you already understand'], mistakes: ['Fake screenshots'], prevSlug: 'series-digital-03-deliver', nextSlug: 'series-digital-05-stack' },
  { slug: 'series-digital-05-stack', title: 'Content + product + affiliate without chaos (Series 4 · Part 5)', summary: 'One niche spine so posts and offers reinforce each other.', category: 'opportunities', series: 'digital', part: 5, reading_minutes: 10, intro: 'Example spine: short-form editing help → CapCut posts → template product → tool you truly use.', bullets: ['One niche', 'Posts teach', 'Product helps', 'Affiliate matches'], steps: ['Write your spine in four bullets'], mistakes: ['New personality every week'], prevSlug: 'series-digital-04-affiliate' },
  { slug: 'series-scam-01-x-noise', title: 'X airdrop noise: how to read it safely (Series 5 · Part 1)', summary: 'Trending claim posts are common — filter before you click or connect.', category: 'scams', series: 'scam', part: 1, reading_minutes: 14, intro: 'Busy days on X fill with comment-your-address posts, every-wallet-gets claims, and countdown pressure. Some are clumsy, some polished. This guide is a beginner filter for high-pressure styles — not a claim that every airdrop discussion is fake.', bullets: ['Engagement farming rewards reply chains', 'FOMO compresses decision time', 'Screenshots are cheap to fake', 'Seed phrase ask → stop', 'Pay to unlock withdrawal → stop', 'Only proof is thread screenshots → pause', 'Countdown plus insults → social pressure not diligence'], steps: ['Type project names yourself', 'Avoid link shorteners in hype replies', 'If heart rate is up, close the app ten minutes'], mistakes: ['Acting inside the thread without outside verification', 'Connecting a main wallet to experiment'], nextSlug: 'series-scam-02-wallet' },
  { slug: 'series-scam-02-wallet', title: 'Wallet hygiene for curious beginners (Series 5 · Part 2)', summary: 'Separate experiments from savings. Never share recovery phrases.', category: 'scams', series: 'scam', part: 2, reading_minutes: 12, intro: 'Connect wallet is not a casual login. You may grant permissions. If you do not understand the screen, do not approve.', bullets: ['Never type seed phrases from chat links', 'Use a small separate wallet for experiments if any', 'Prefer official stores and typed URLs', 'Avoid random APKs from chat files'], steps: ['Review what apps can access on your phone', 'Write a personal rule: no seed phrase ever on websites from replies'], mistakes: ['Using savings wallet for experiments'], prevSlug: 'series-scam-01-x-noise', nextSlug: 'series-scam-03-jobs' },
  { slug: 'series-scam-03-jobs', title: 'Fake remote jobs and task traps (Series 5 · Part 3)', summary: 'Rising dashboards then a fee to withdraw — memorize the loop.', category: 'scams', series: 'scam', part: 3, reading_minutes: 12, intro: 'Simple tasks, rising balance, fee to withdraw, sometimes a second fee. That is extraction, not employment. Real hiring is usually slower and more boring.', bullets: ['Pay for equipment to personal accounts', 'Only consumer chat contact', 'Extreme pay for trivial skill'], steps: ['Save this pattern in your notes', 'Refuse pay-to-withdraw work'], mistakes: ['Believing dashboard numbers without withdrawal proof'], prevSlug: 'series-scam-02-wallet', nextSlug: 'series-scam-04-telegram' },
  { slug: 'series-scam-04-telegram', title: 'Telegram pressure plays and fake admins (Series 5 · Part 4)', summary: 'Urgency and private support that request payment.', category: 'scams', series: 'scam', part: 4, reading_minutes: 11, intro: 'Admins who message first with urgency, move you private quickly, and frame payment as the only fix are a pattern worth recognizing.', bullets: ['Screenshots replace process', 'You may insist on public official instructions only'], steps: ['Practice a calm refusal script'], mistakes: ['Paying to unlock support'], prevSlug: 'series-scam-03-jobs', nextSlug: 'series-scam-05-recovery' },
  { slug: 'series-scam-05-recovery', title: 'After a loss: avoid recovery scams (Series 5 · Part 5)', summary: 'Helpers who promise reversal for a fee are often the second hit.', category: 'scams', series: 'scam', part: 5, reading_minutes: 11, intro: 'After a loss, recovery experts appear. Many deepen the damage. Paying them is usually another extraction.', bullets: ['Write what happened while details are fresh', 'Warn your circle', 'Ignore paid recovery DMs'], steps: ['Document once offline', 'Do not engage recovery DMs'], mistakes: ['Sending more money to undo the first loss'], prevSlug: 'series-scam-04-telegram' },
  { slug: 'series-money-01-discipline', title: 'Discipline over another hustle (Series 6 · Part 1)', summary: 'Money systems often beat stacking more apps.', category: 'money', series: 'money', part: 1, reading_minutes: 11, intro: 'Some of the most useful posts online are not new hustles. Without a basic money system, opportunities leak through fees and unfinished experiments.', bullets: ['Weekly review', 'Buffer goal', 'Rules about what you will not fund while learning'], steps: ['Write three personal money rules'], mistakes: ['Funding every new app while bills are unclear'], nextSlug: 'series-money-02-weekly-review' },
  { slug: 'series-money-02-weekly-review', title: 'A 20-minute weekly money review (Series 6 · Part 2)', summary: 'Cash in after fees, bills out, one practice goal.', category: 'money', series: 'money', part: 2, reading_minutes: 10, intro: 'Same day each week. Notes app is enough. Accuracy beats fancy dashboards.', bullets: ['Income after fees', 'Must-pay bills', 'One skill goal', 'Noise spending'], steps: ['Put a recurring reminder'], mistakes: ['Skipping weeks then guessing'], prevSlug: 'series-money-01-discipline', nextSlug: 'series-money-03-freelance-offer' },
  { slug: 'series-money-03-freelance-offer', title: 'Write a one-sentence freelance offer (Series 6 · Part 3)', summary: 'Clear offers get clearer replies.', category: 'opportunities', series: 'money', part: 3, reading_minutes: 11, intro: 'Template: I help [person] get [result] with [method] so they can [outcome]. If a stranger cannot repeat it, simplify.', bullets: ['Specific person', 'Specific result', 'Specific method'], steps: ['Write three versions', 'Pick the clearest'], mistakes: ['Vague I do digital marketing lines'], prevSlug: 'series-money-02-weekly-review', nextSlug: 'series-money-04-first-outreach' },
  { slug: 'series-money-04-first-outreach', title: 'First outreach without spam energy (Series 6 · Part 4)', summary: 'Specific messages, a sample, and a graceful stop.', category: 'opportunities', series: 'money', part: 4, reading_minutes: 11, intro: 'One true detail about them, one-sentence offer, sample, easy no. Ten thoughtful messages beat a hundred copy-pastes.', bullets: ['Respect time', 'Track replies not fantasies'], steps: ['Send five careful messages with your sample'], mistakes: ['Blast lists with the same paragraph'], prevSlug: 'series-money-03-freelance-offer' },
];
